[package]
name = "hassan"
version = "0.1.0"
authors = ["bart"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.5"
fastrand = "2.0.2"

[build-dependencies]
slint-build = "1.5"
