import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <int> dices: 0;
    in property <string> hassan: "";
    callback dices-rolled();

    width: 200px;
    height: 240px;

    background: #313e50;
    GridLayout {
        padding: 20px;
        spacing: 15px;
        Row {
            Button {
                text: "Roll the dice!";   
                primary: true;
                clicked => {dices-rolled()}
            }
        }
        
        Row {
            VerticalBox {
                Rectangle {
                    height: 50px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-weight: 500;
                        text: root.dices;                        
                    }
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 50px;
                    background: #f2f2f2;
                    Text {
                        color: black;
                        font-size: 12px;
                        font-weight: 500;
                        text: root.hassan;                        
                    }
                }
            }
        }
    }

/*     in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
 */}
